import { Anek_Bangla } from "next/font/google";
import "./globals.css";

const anekBangla = Anek_Bangla({
  variable: "--anek-bangla",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Daily Talim",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_dark.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body className={`${anekBangla.className} antialiased`}>{children}</body>
    </html>
  );
}
